### ISSUE TITLE
error in Sequence_Allele_Call.py

### ISSUE THREAD

**Issue by amandaamelo** [mcurto/SSR-GBS-pipeline#4]
Hi Manuel, it's me again!

I'm trying to run the last script of the pipeline, Sequence_Allele_Call.py.

The parameter file I am using is attached here.

[SSR-GBS_pipeline_paramter_file_BarPilotoA7D30.txt](https://github.com/mcurto/SSR-GBS-pipeline/files/13268965/SSR-GBS_pipeline_paramter_file_BarPilotoA7D30.txt)

My command line for this step is:
python3 Sequence_Allele_Call.py SSR-GBS_pipeline_paramter_file_BarPilotoA7D30.txt

However, the script cannot seem to find the files in the folder of the demultiplexed files from script 1. I'm getting the following error message:
Creation of the directory /media/lgbio-nas1/amandamelo/SSR-GBS-Bra-Piloto/SSR-GBS-Bra-Piloto-27-10-23-401900626/Tibihika-Pipeline/A07D30-SNP-Call/AllelesOut
Creation of the directory /media/lgbio-nas1/amandamelo/SSR-GBS-Bra-Piloto/SSR-GBS-Bra-Piloto-27-10-23-401900626/Tibihika-Pipeline/A07D30-SNP-Call/ConsensusOut
Creation of the directory /media/lgbio-nas1/amandamelo/SSR-GBS-Bra-Piloto/SSR-GBS-Bra-Piloto-27-10-23-401900626/Tibihika-Pipeline/A07D30-SNP-Call/ConsensusTogether
Creation of the directory /media/lgbio-nas1/amandamelo/SSR-GBS-Bra-Piloto/SSR-GBS-Bra-Piloto-27-10-23-401900626/Tibihika-Pipeline/A07D30-SNP-Call/Corrected
Creation of the directory /media/lgbio-nas1/amandamelo/SSR-GBS-Bra-Piloto/SSR-GBS-Bra-Piloto-27-10-23-401900626/Tibihika-Pipeline/A07D30-SNP-Call/AlleleCall
processing sample samplename
processing sample BarBRI-SP-50S44merged
...processing locus Bhy_SSR-NGS1
......genotype: 219,219
Traceback (most recent call last):
  File "Sequence_Allele_Call.py", line 646, in <module>
    extract_alleles(allelesFile, SeparatOut, fileType, WorkingDir + 'AllelesOut/')
  File "Sequence_Allele_Call.py", line 178, in extract_alleles
    ExtractedSeqs = extractLengthFastq(f, int(al)) # filter sequences (fastq input)
  File "Sequence_Allele_Call.py", line 123, in extractLengthFastq
    for rec, seq in parse_fastq(fastq).items():
  File "Sequence_Allele_Call.py", line 60, in parse_fastq
    f = open(fastq)
FileNotFoundError: [Errno 2] No such file or directory: '/media/lgbio-nas1/amandamelo/SSR-GBS-Bra-Piloto/SSR-GBS-Bra-Piloto-27-10-23-401900626/Tibihika-Pipeline/demultiplex-BarPiloto/BarBRI-SP-50S44merged_Bhy_SSR-NGS1.fastq'

However, the files in the demultiplex-BarPiloto folder are named with the motif repetition in the end of it (BarBRI-SP-50S44merged_Bhy_SSR-NGS1_ATGG.fastq).

I'm thinking it is returning this error due to the name file divergence. However, script 1 requires us to inform the marker name with the motif repetition in the end (e.g.Bhy_SSR-NGS1_ATGG), and it is how the demultiplexed files are named as output.

I tried renaming the locus name on the output.matrix.csv (output from script #3) for MarkerName_Motif but script #4 still searches for files with MarkerName only. 

I haven't tried running script #1 again with the marker name without the motif repeat information because it is explicitly a request to run script #1.

I'm sorry if it is a silly error and question but I can't seem to figure out how to solve it.

Thank you in advance and hope to hear from you soon!

**Comment by mcurto** [comment]
Hi Amanda,
Can you send me the marker file you are using for the demultiplex? Pretty much the marker names should me structure the following way: Name_motif. The name should not have any underscore ("_") sign because it uses it as a separator. I think in your case the problem is the fact that you have an underscore after Bhy. The program is assuming that Bhy is the marker name and SSR-NGS1 the motif.
Best,
Manuel

**Comment by amandaamelo** [comment]
[locus_BarPiloto-Tibihika.txt](https://github.com/mcurto/SSR-GBS-pipeline/files/13271707/locus_BarPiloto-Tibihika.txt)
Oh, I see!

I thought the underscore could not be present only in the fastq files. That's why then.

I'll replace the underscore on the marker name files and I'll try again. Anyway, I'm sending you the marker file for script #1 
Thanks again! I'll let you know when I try again

**Comment by amandaamelo** [comment]
That was indeed the problem! I re-ran all scripts with the marker names without the underscore and it worked!

Thanks for the quick help again!
